//===-- ClangTypeConverterTest.cpp ---------------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#include "ClangASTGeneratorTestUtils.h"

#include "Plugins/ExpressionParser/Clang/ClangTypeConverter.h"
#include "Plugins/TypeSystem/Clike/Type.h"

#include "clang/AST/ASTContext.h"

#include "llvm/Testing/Support/Error.h"

using namespace lldb_private;
using namespace lldb_private::clike_typesystem;

namespace {
using ClangTypeConverterTest = ClangASTGeneratorTestUtils;
} // namespace

// Converting a clang type that was generated from a cpp type maps back to the
// exact same cpp CompilerType via the generator's reverse map.
TEST_F(ClangTypeConverterTest, RoundTripGeneratedType) {
  ClangASTGenerator generator(ast);
  ClangTypeConverter converter(generator, *ts);

  CompilerType record = builder.CreateRecordType("Foo", 4, false);
  clang::QualType qt = generator.Generate(record);

  CompilerType back = converter.Convert(qt);
  ASSERT_TRUE(back.IsValid());
  EXPECT_EQ(back.GetOpaqueQualType(), record.GetOpaqueQualType());
}

// A plain clang builtin the parser formed on its own (not generated by us,
// e.g. the result of `1 + 1`) maps onto the TypeSystemClike `int` builtin.
TEST_F(ClangTypeConverterTest, ConvertPlainBuiltin) {
  ClangASTGenerator generator(ast);
  ClangTypeConverter converter(generator, *ts);

  CompilerType converted = converter.Convert(ast.IntTy);
  ASSERT_TRUE(converted.IsValid());
  bool is_signed = false;
  EXPECT_TRUE(converted.IsIntegerType(is_signed));
  llvm::Expected<uint64_t> byte_size = converted.GetByteSize(nullptr);
  ASSERT_THAT_EXPECTED(byte_size, llvm::Succeeded());
  EXPECT_EQ(*byte_size, 4u);
}

// A record the parser defined itself (not generated by us) is rebuilt as an
// equivalent (complete) cpp record with the same fields.
TEST_F(ClangTypeConverterTest, ConvertParserDefinedRecord) {
  ClangASTGenerator generator(ast);
  ClangTypeConverter converter(generator, *ts);

  auto *decl = clang::CXXRecordDecl::Create(
      ast, clang::TagTypeKind::Struct, ast.getTranslationUnitDecl(),
      clang::SourceLocation(), clang::SourceLocation(),
      &ast.Idents.get("ParserStruct"));
  decl->startDefinition();
  auto *field = clang::FieldDecl::Create(
      ast, decl, clang::SourceLocation(), clang::SourceLocation(),
      &ast.Idents.get("member"), ast.IntTy, nullptr, nullptr, false,
      clang::ICIS_NoInit);
  field->setAccess(clang::AS_public);
  decl->addDecl(field);
  decl->completeDefinition();
  clang::QualType qt = ast.getCanonicalTagType(decl);

  CompilerType converted = converter.Convert(qt);
  ASSERT_TRUE(converted.IsValid());
  EXPECT_EQ(converted.GetTypeName().GetStringRef(), "ParserStruct");
  ASSERT_EQ(converted.GetNumFields(), 1u);
  std::string name;
  converted.GetFieldAtIndex(0, name, nullptr, nullptr, nullptr);
  EXPECT_EQ(name, "member");
}

// A pointer/reference the parser formed on its own (not generated by us)
// round-trips to a cpp pointer/reference over the recursively-converted
// pointee.
TEST_F(ClangTypeConverterTest, ConvertParserDefinedPointerAndReference) {
  ClangASTGenerator generator(ast);
  ClangTypeConverter converter(generator, *ts);

  clang::QualType ptr_qt = ast.getPointerType(ast.IntTy);
  CompilerType ptr = converter.Convert(ptr_qt);
  ASSERT_TRUE(ptr.IsValid());
  EXPECT_TRUE(ptr.IsPointerType());

  clang::QualType ref_qt = ast.getLValueReferenceType(ast.IntTy);
  CompilerType ref = converter.Convert(ref_qt);
  ASSERT_TRUE(ref.IsValid());
  bool is_rvalue = true;
  EXPECT_TRUE(ref.IsReferenceType(nullptr, &is_rvalue));
  EXPECT_FALSE(is_rvalue);
}

// A cv-qualifier the parser applied that we didn't generate ourselves (e.g.
// on a plain builtin) is preserved by wrapping the mapped unqualified type.
TEST_F(ClangTypeConverterTest, ConvertPreservesUnknownQualifiers) {
  ClangASTGenerator generator(ast);
  ClangTypeConverter converter(generator, *ts);

  clang::QualType const_int = ast.IntTy;
  const_int.addConst();
  CompilerType converted = converter.Convert(const_int);
  ASSERT_TRUE(converted.IsValid());
  EXPECT_TRUE(converted.IsConst());
}

// Converting a null QualType yields an invalid CompilerType instead of
// crashing.
TEST_F(ClangTypeConverterTest, ConvertNullIsInvalid) {
  ClangASTGenerator generator(ast);
  ClangTypeConverter converter(generator, *ts);
  EXPECT_FALSE(converter.Convert(clang::QualType()).IsValid());
}
