#include "plugin.h"

// Generated by gen_tags.py (see the Makefile): defines the primary template
// 'Tag' (and its 'Tag<0>' base case), and force-instantiates 'Tag<N>' for
// every EVEN N in [1, 200] as a global variable in the 'main_storm'
// namespace. Each 'Tag<N>' implicitly instantiates 'Tag<N-1>' (through the
// 'prev' member), which implicitly instantiates 'Tag<N-2>', and so on down
// to 'Tag<0>' - so main.cpp's debug info actually ends up describing
// (implicit instantiations of) *every* N in [0, 200], not just the even
// ones whose globals live here.
#include "tag_main_gen.h"

int main() {
  plugin_init();
  plugin_entry();
  return 0;
}
