#include "plugin.h"

// Generated by gen_tags.py (see the Makefile): defines the same primary
// template 'Tag' (and its 'Tag<0>' base case) as main.cpp, but additionally
// provides an EXPLICIT specialization 'Tag<N>' for every ODD N in [1, 200]
// with 'prev' and 'arr' swapped relative to the primary template's member
// order (which is what main.cpp's implicit instantiations use). This is a
// genuine ODR violation on every odd 'Tag<N>': the same specialization has
// two different definitions depending on which module's debug info you
// look at.
//
// This header also force-instantiates 'Tag<N>' for every ODD N in [1, 200]
// as a global variable in the 'plugin_storm' namespace, using plugin.cpp's
// own conflicting explicit specializations.
#include "tag_plugin_gen.h"

extern "C" {
void plugin_init(void) {}
void plugin_entry(void) {}
}
