//===-- ClangASTGenerator.h -------------------------------------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef LLDB_SOURCE_PLUGINS_EXPRESSIONPARSER_CLANG_CLANGASTGENERATOR_H
#define LLDB_SOURCE_PLUGINS_EXPRESSIONPARSER_CLANG_CLANGASTGENERATOR_H

#include "lldb/Symbol/CompilerType.h"
#include "lldb/lldb-forward.h"

#include "clang/AST/CharUnits.h"
#include "clang/AST/Type.h"
#include "llvm/ADT/DenseMap.h"

namespace clang {
class ASTContext;
class RecordDecl;
class CXXRecordDecl;
class FieldDecl;
class FunctionDecl;
class TagDecl;
} // namespace clang

namespace lldb_private {

class TypeSystemCpp;

namespace cpp_typesystem {
class Type;
class RecordType;
} // namespace cpp_typesystem

/// Translates types from the module-level TypeSystemCpp (see the
/// cpp_typesystem::Type hierarchy) into a Clang AST, so that LLDB's Clang-based
/// expression parser can reason about them.
///
/// This is the TypeSystemCpp counterpart of what the ASTImporter does for the
/// Clang module type system: it materializes clang::Decls/QualTypes for the
/// entities referenced by an expression. Unlike the importer, it never copies
/// from another Clang AST; it synthesizes the AST from scratch out of the
/// (Clang-AST-free) cpp_typesystem description, writing directly into a
/// clang::ASTContext. It intentionally does not depend on TypeSystemClang.
///
/// Records are created lazily as forward declarations and are completed (and
/// laid out) on demand, mirroring how debug info is parsed lazily. The
/// generator also keeps the reverse mapping (generated Clang type ->
/// originating cpp_typesystem type) so an expression's result type can be
/// mapped back onto a TypeSystemCpp type without ever translating Clang types
/// back.
class ClangASTGenerator {
public:
  explicit ClangASTGenerator(clang::ASTContext &ast) : m_ast(ast) {}

  /// Translate \p cpp_type (a CompilerType owned by a TypeSystemCpp) into a
  /// clang::QualType. Returns a null QualType on failure.
  clang::QualType Generate(const CompilerType &cpp_type);

  /// Complete a record previously handed out by Generate(). Called by the
  /// external source when Clang requires the full definition. Returns true if
  /// \p tag_decl was created by this generator (and is now complete).
  bool CompleteRecord(clang::TagDecl *tag_decl);

  /// Provide the debug-info layout for a record created by this generator.
  /// Returns false when the record is unknown (letting Clang lay it out).
  bool LayoutRecord(
      const clang::RecordDecl *record_decl, uint64_t &size, uint64_t &alignment,
      llvm::DenseMap<const clang::FieldDecl *, uint64_t> &field_offsets,
      llvm::DenseMap<const clang::CXXRecordDecl *, clang::CharUnits>
          &base_offsets,
      llvm::DenseMap<const clang::CXXRecordDecl *, clang::CharUnits>
          &vbase_offsets);

  /// Map a Clang type produced by this generator back to its cpp_typesystem
  /// origin. Returns an invalid CompilerType if the type wasn't generated by
  /// us. The returned CompilerType is owned by \p result_ts (typically the
  /// scratch TypeSystemCpp), so it can be stored as an expression result.
  CompilerType MapClangTypeToCpp(clang::QualType qt, TypeSystemCpp &result_ts);

  /// Build a clang::FunctionDecl (in the translation unit) for a free function
  /// with the given signature and asm label; the JIT resolves the call through
  /// the label. Returns null on failure.
  clang::FunctionDecl *GenerateFunction(llvm::StringRef name,
                                        const CompilerType &function_cpp_type,
                                        llvm::StringRef asm_label);

private:
  /// Generate the clang type for \p cpp_type, which is owned by \p ts.
  clang::QualType GenerateType(TypeSystemCpp &ts, cpp_typesystem::Type *cpp_type);

  /// Complete a record's fields/bases from its cpp_typesystem description.
  void PopulateRecord(clang::RecordDecl *record_decl);

  /// Complete any record type embedded by value in \p qt (the type itself, or
  /// an array element) so it can be used as a base/field.
  void EnsureComplete(clang::QualType qt);

  /// Map a cpp_typesystem builtin type to a Clang builtin QualType.
  clang::QualType GenerateBuiltin(cpp_typesystem::Type *cpp_type);

  /// Create ParmVarDecls for \p func from the parameter types of \p function_qt
  /// (a FunctionProtoType).
  void BuildParams(clang::FunctionDecl *func, clang::QualType function_qt);

  clang::ASTContext &m_ast;

  /// cpp_typesystem::Type -> produced clang QualType (opaque pointer).
  llvm::DenseMap<cpp_typesystem::Type *, void *> m_generated;

  /// Reverse map: opaque QualType (quals included) -> originating
  /// cpp_typesystem::Type, so cv-qualified variants stay distinct.
  llvm::DenseMap<void *, cpp_typesystem::Type *> m_reverse;

  /// Per-record bookkeeping for lazy completion and layout.
  struct RecordInfo {
    TypeSystemCpp *ts = nullptr;
    cpp_typesystem::RecordType *cpp_record = nullptr;
    clang::CXXRecordDecl *clang_decl = nullptr;
    bool completed = false;
  };
  llvm::DenseMap<const clang::RecordDecl *, RecordInfo> m_records;
};

} // namespace lldb_private

#endif // LLDB_SOURCE_PLUGINS_EXPRESSIONPARSER_CLANG_CLANGASTGENERATOR_H
