//===-- ClangASTGenerator.h -------------------------------------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef LLDB_SOURCE_PLUGINS_EXPRESSIONPARSER_CLANG_CLANGASTGENERATOR_H
#define LLDB_SOURCE_PLUGINS_EXPRESSIONPARSER_CLANG_CLANGASTGENERATOR_H

#include "lldb/Symbol/CompilerType.h"
#include "lldb/lldb-forward.h"

#include "clang/AST/CharUnits.h"
#include "clang/AST/Type.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/TargetParser/Triple.h"

#include <memory>

namespace clang {
class ASTContext;
class DeclContext;
class NamespaceDecl;
class RecordDecl;
class CXXRecordDecl;
class FieldDecl;
class FunctionDecl;
class TagDecl;
} // namespace clang

namespace lldb_private {

class TypeSystemCpp;

namespace cpp_typesystem {
class Type;
class RecordType;
class Namespace;
} // namespace cpp_typesystem

/// Translates types from the module-level TypeSystemCpp (see the
/// cpp_typesystem::Type hierarchy) into a Clang AST, so that LLDB's Clang-based
/// expression parser can reason about them.
///
/// This is the TypeSystemCpp counterpart of what the ASTImporter does for the
/// Clang module type system: it materializes clang::Decls/QualTypes for the
/// entities referenced by an expression. Unlike the importer, it never copies
/// from another Clang AST; it synthesizes the AST from scratch out of the
/// (Clang-AST-free) cpp_typesystem description, writing directly into a
/// clang::ASTContext. It intentionally does not depend on TypeSystemClang.
///
/// Records are created lazily as forward declarations and are completed (and
/// laid out) on demand, mirroring how debug info is parsed lazily. The
/// generator also keeps the reverse mapping (generated Clang type ->
/// originating cpp_typesystem type) so an expression's result type can be
/// mapped back onto a TypeSystemCpp type without ever translating Clang types
/// back.
class ClangASTGenerator {
public:
  explicit ClangASTGenerator(clang::ASTContext &ast) : m_ast(ast) {}

  /// Dump a Clang AST of \p records (record CompilerTypes owned by \p ts) to
  /// \p output, applying \p filter (a name substring; empty means no filter).
  /// Builds a standalone, throwaway clang::ASTContext for the module's \p
  /// triple, synthesizes a definition for each record into it, and prints it
  /// with clang's AST dumper. This backs `target modules dump ast` for
  /// TypeSystemCpp (the Clang-AST synthesis has to live in this plugin).
  static void DumpRecords(TypeSystemCpp &ts, const llvm::Triple &triple,
                          llvm::ArrayRef<CompilerType> records,
                          llvm::raw_ostream &output, llvm::StringRef filter,
                          bool show_color);

  /// Translate \p cpp_type (a CompilerType owned by a TypeSystemCpp) into a
  /// clang::QualType. Returns a null QualType on failure.
  clang::QualType Generate(const CompilerType &cpp_type);

  /// Complete a record previously handed out by Generate(). Called by the
  /// external source when Clang requires the full definition. Returns true if
  /// \p tag_decl was created by this generator (and is now complete).
  bool CompleteRecord(clang::TagDecl *tag_decl);

  /// Provide the debug-info layout for a record created by this generator.
  /// Returns false when the record is unknown (letting Clang lay it out).
  bool LayoutRecord(
      const clang::RecordDecl *record_decl, uint64_t &size, uint64_t &alignment,
      llvm::DenseMap<const clang::FieldDecl *, uint64_t> &field_offsets,
      llvm::DenseMap<const clang::CXXRecordDecl *, clang::CharUnits>
          &base_offsets,
      llvm::DenseMap<const clang::CXXRecordDecl *, clang::CharUnits>
          &vbase_offsets);

  /// Map a Clang type produced by this generator back to its cpp_typesystem
  /// origin. Returns an invalid CompilerType if the type wasn't generated by
  /// us. The returned CompilerType is owned by \p result_ts (typically the
  /// scratch TypeSystemCpp), so it can be stored as an expression result.
  CompilerType MapClangTypeToCpp(clang::QualType qt, TypeSystemCpp &result_ts);

  /// Build a clang::FunctionDecl (in the translation unit) for a free function
  /// with the given signature and asm label; the JIT resolves the call through
  /// the label. Returns null on failure.
  clang::FunctionDecl *GenerateFunction(llvm::StringRef name,
                                        const CompilerType &function_cpp_type,
                                        llvm::StringRef asm_label);

  /// True while this generator is actively synthesizing clang decls. Adding a
  /// named decl to the (external-visible) translation unit makes clang
  /// reconcile that name against the external source; those reentrant lookups
  /// are internal bookkeeping, not genuine references from the expression, so
  /// callers use this to skip expensive global searches while it is set. See
  /// CppExpressionDeclMap::FindExternalVisibleDecls.
  bool IsGenerating() const { return m_generation_depth != 0; }

  /// Register the clang::NamespaceDecl that the decl map created for the
  /// cpp_typesystem namespace \p cpp_ns. Types whose declaration context is
  /// \p cpp_ns are then generated inside \p clang_ns (rather than the
  /// translation unit) so their qualified names mangle correctly for the JIT.
  void RegisterNamespace(const cpp_typesystem::Namespace *cpp_ns,
                         clang::NamespaceDecl *clang_ns);

  /// The clang DeclContext a type declared in \p cpp_ns should be placed in:
  /// the registered clang::NamespaceDecl if one exists, otherwise the
  /// translation unit (the global namespace, or a namespace not yet mapped).
  clang::DeclContext *
  GetDeclContextForNamespace(const cpp_typesystem::Namespace *cpp_ns);

private:
  /// RAII marker for IsGenerating(): held for the duration of each public
  /// AST-synthesizing entry point (so nested/recursive generation stays
  /// "generating" until the outermost call returns).
  class GenerationGuard {
  public:
    explicit GenerationGuard(ClangASTGenerator &gen) : m_gen(gen) {
      ++m_gen.m_generation_depth;
    }
    ~GenerationGuard() { --m_gen.m_generation_depth; }
    GenerationGuard(const GenerationGuard &) = delete;
    GenerationGuard &operator=(const GenerationGuard &) = delete;

  private:
    ClangASTGenerator &m_gen;
  };

  /// Generate the clang type for \p cpp_type, which is owned by \p ts.
  clang::QualType GenerateType(TypeSystemCpp &ts, cpp_typesystem::Type *cpp_type);

  /// Complete a record's fields/bases from its cpp_typesystem description.
  void PopulateRecord(clang::RecordDecl *record_decl);

  /// Complete any record type embedded by value in \p qt (the type itself, or
  /// an array element) so it can be used as a base/field.
  void EnsureComplete(clang::QualType qt);

  /// Map a cpp_typesystem builtin type to a Clang builtin QualType.
  clang::QualType GenerateBuiltin(cpp_typesystem::Type *cpp_type);

  /// Create ParmVarDecls for \p func from the parameter types of \p function_qt
  /// (a FunctionProtoType).
  void BuildParams(clang::FunctionDecl *func, clang::QualType function_qt);

  clang::ASTContext &m_ast;

  /// Nonzero while inside a public AST-synthesizing entry point. See
  /// IsGenerating() / GenerationGuard.
  unsigned m_generation_depth = 0;

  /// cpp_typesystem::Type -> produced clang QualType (opaque pointer).
  llvm::DenseMap<cpp_typesystem::Type *, void *> m_generated;

  /// cpp_typesystem::Namespace -> the clang::NamespaceDecl the decl map created
  /// for it, so generated types are placed in the matching namespace.
  llvm::DenseMap<const cpp_typesystem::Namespace *, clang::NamespaceDecl *>
      m_namespaces;

  /// Reverse map: opaque QualType (quals included) -> originating
  /// cpp_typesystem::Type, so cv-qualified variants stay distinct.
  llvm::DenseMap<void *, cpp_typesystem::Type *> m_reverse;

  /// Per-record bookkeeping for lazy completion and layout.
  struct RecordInfo {
    TypeSystemCpp *ts = nullptr;
    cpp_typesystem::RecordType *cpp_record = nullptr;
    clang::CXXRecordDecl *clang_decl = nullptr;
    bool completed = false;
    /// Bit offset of every field decl we added while populating this record,
    /// including the synthetic unnamed bitfields inserted to fill the gaps left
    /// by DWARF's omitted padding bitfields. LayoutRecord reports these to
    /// Clang (a plain parallel walk of the cpp fields wouldn't account for the
    /// synthetic ones).
    llvm::DenseMap<const clang::FieldDecl *, uint64_t> field_bit_offsets;
  };
  // Values are held behind unique_ptr so a RecordInfo& stays valid across the
  // recursive GenerateType/completion calls that insert new entries here (a
  // DenseMap rehash would otherwise invalidate references into it).
  llvm::DenseMap<const clang::RecordDecl *, std::unique_ptr<RecordInfo>>
      m_records;
};

} // namespace lldb_private

#endif // LLDB_SOURCE_PLUGINS_EXPRESSIONPARSER_CLANG_CLANGASTGENERATOR_H
