//===-- ClangASTGenerator.h -------------------------------------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef LLDB_SOURCE_PLUGINS_EXPRESSIONPARSER_CLANG_CLANGASTGENERATOR_H
#define LLDB_SOURCE_PLUGINS_EXPRESSIONPARSER_CLANG_CLANGASTGENERATOR_H

#include "lldb/Symbol/CompilerType.h"
#include "lldb/lldb-forward.h"

#include "clang/AST/CharUnits.h"
#include "clang/AST/Type.h"
#include "llvm/ADT/DenseMap.h"

namespace clang {
class RecordDecl;
class CXXRecordDecl;
class FieldDecl;
class TagDecl;
} // namespace clang

namespace lldb_private {

class TypeSystemClang;
class TypeSystemCpp;

namespace cpp_typesystem {
class Type;
class RecordType;
} // namespace cpp_typesystem

/// Translates types from the module-level TypeSystemCpp (see the
/// cpp_typesystem::Type hierarchy) into a clang AST living in a
/// TypeSystemClang, so that LLDB's Clang-based expression parser can reason
/// about them.
///
/// This is the TypeSystemCpp counterpart of what the ASTImporter does for the
/// Clang module type system: it materializes clang::Decls/QualTypes for the
/// entities referenced by an expression. Unlike the importer, it never copies
/// from another clang AST; instead it synthesizes the AST from scratch out of
/// the (Clang-AST-free) cpp_typesystem description.
///
/// Records are created lazily as forward declarations and are completed (and
/// laid out) on demand, mirroring how debug info is parsed lazily. The
/// generator also keeps the reverse mapping (generated clang type ->
/// originating cpp_typesystem type) so an expression's result type can be
/// mapped back onto a TypeSystemCpp type without ever translating clang types
/// back.
class ClangASTGenerator {
public:
  explicit ClangASTGenerator(TypeSystemClang &clang_ast)
      : m_clang_ast(clang_ast) {}

  /// Translate \p cpp_type (a CompilerType owned by a TypeSystemCpp) into a
  /// CompilerType in the target TypeSystemClang. Returns an invalid type on
  /// failure.
  CompilerType Generate(const CompilerType &cpp_type);

  /// Complete a record previously handed out by Generate(). Called by the
  /// external source when Clang requires the full definition. Returns true if
  /// \p tag_decl was created by this generator (and is now complete).
  bool CompleteRecord(clang::TagDecl *tag_decl);

  /// Provide the debug-info layout for a record created by this generator.
  /// Returns false when the record is unknown (letting Clang lay it out).
  bool LayoutRecord(
      const clang::RecordDecl *record_decl, uint64_t &size, uint64_t &alignment,
      llvm::DenseMap<const clang::FieldDecl *, uint64_t> &field_offsets,
      llvm::DenseMap<const clang::CXXRecordDecl *, clang::CharUnits>
          &base_offsets,
      llvm::DenseMap<const clang::CXXRecordDecl *, clang::CharUnits>
          &vbase_offsets);

  /// Map a clang type produced by this generator back to its cpp_typesystem
  /// origin. Returns an invalid CompilerType if the type wasn't generated by
  /// us. The returned CompilerType is owned by \p result_ts (typically the
  /// scratch TypeSystemCpp), so it can be stored as an expression result.
  CompilerType MapClangTypeToCpp(clang::QualType qt, TypeSystemCpp &result_ts);

private:
  /// Generate the clang type for \p cpp_type, which is owned by \p ts.
  CompilerType GenerateType(TypeSystemCpp &ts, cpp_typesystem::Type *cpp_type);

  /// Complete a record's fields/bases from its cpp_typesystem description.
  void PopulateRecord(clang::RecordDecl *record_decl);

  /// Complete any record type embedded by value in \p clang_type (the type
  /// itself, or an array element) so it can be used as a base/field.
  void EnsureComplete(const CompilerType &clang_type);

  TypeSystemClang &m_clang_ast;

  /// cpp_typesystem::Type -> produced clang QualType (opaque pointer).
  llvm::DenseMap<cpp_typesystem::Type *, lldb::opaque_compiler_type_t>
      m_generated;

  /// Reverse map: canonical clang type -> originating cpp_typesystem::Type.
  llvm::DenseMap<const clang::Type *, cpp_typesystem::Type *> m_reverse;

  /// Per-record bookkeeping for lazy completion and layout.
  struct RecordInfo {
    TypeSystemCpp *ts = nullptr;
    cpp_typesystem::RecordType *cpp_record = nullptr;
    CompilerType clang_type;
    bool completed = false;
  };
  llvm::DenseMap<const clang::RecordDecl *, RecordInfo> m_records;
};

} // namespace lldb_private

#endif // LLDB_SOURCE_PLUGINS_EXPRESSIONPARSER_CLANG_CLANGASTGENERATOR_H
